enum ENUM_LOGIC_RESULT {
  LOGIC_RESULT_OPEN_LONG,
  LOGIC_RESULT_OPEN_SHORT,
  LOGIC_RESULT_FLAT,
  LOGIC_RESULT_CLOSE_LONG,
  LOGIC_RESULT_CLOSE_SHORT
};

interface LogicInterface {
public:
  ENUM_LOGIC_RESULT execute();
};
